# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.12"
  commands:
    - python -m pip install sphinx-rtd-theme
python:
  install:
    - method: poetry
      requirements: pyproject.toml
      path: .
sphinx:
  configuration: docs/conf.py
